### ISSUE TITLE
ConnectionType in NEAT's Genome

### ISSUE THREAD

**Issue by Lunderberg** [ArtificialEvolvingWorld/Entendre#1]
Since the NeuralNet decides for itself whether a connection needs to be recurrent or not, it is rather confusing to have it present.  I propose that we remove it, since the genome's type may not match that of the generated neural net.

**Comment by csullivan** [comment]
Agree, completely. It's on my to do list, however, I wanted to check the NEAT publication first to ensure that no genome level mutations or crossover operations require this information, as it would not be ideal to need to construct the NeuralNet, just to determine this information if necessary. That said, I do not think such a dependency exists, but it is why I have not yet removed it from the public interface.

**Comment by csullivan** [comment]
ConnectionType was removed from Genome::AddConnection. Note that from the Genome, there is no distinction between connection types. It is only in NeuralNet where the distinction arises. Thus, the order of Connection creation when building the network is important. All normal connections should be added first, and then all recurrent connections, otherwise a recurrent connection will be added as normal in the network, and vice-versa.

**Comment by csullivan** [comment]
In writing the above comment I realized that the loop over the parent genes during cross over was done over the unordered_map, not the vector of keys, and so the order of insertion wasn't preserved. I fixed this in commit: fa3e5ad0da0ff84c0187d703ea981b12d775a43f (see for more details). As mentioned above, this is a side effect of not storing the connection type in the genome.
